= 氏名の電子的表記
:doctype: article
:lang: ja
:toc:
:toclevels: 1
:revnumber: 1.0
:revdate: 2026-09-10

== 目的

本文書は、私の名前を電子的に表記する場合の表記方法を規定する。

本文書の規定は、適用可能な範囲において非電子的媒体における氏名表記についても適用する。

== 用語

=== 正規表記

本人が意図する標準的な表記をいう。

特段の制約がない場合、正規表記を使用することが望ましい。

=== 許容表記

正規表記とは異なるが、本人の氏名の表記として許容する表記をいう。

=== 任意

当該要素について、本人が表記方法を指定しないことをいう。

「任意」は、本文書に規定が存在しないことを意味しない。

=== 規定なし

本文書において、当該事項の表記方法を規定しないことをいう。

=== 表現不能

対象となる文字集合または符号化体系において、意図する表記を表現できないことをいう。

== 正規表記

本節は、本文書における氏名の正規表記を要約して示す。

氏名::
犬飼規雄

姓（family name）::
犬飼

名（given name）::
規雄

読み::
いぬかいのりお

氏名順::
姓、名（family name, given name）

区切り文字::
区切りなし

ISO/IEC 646 による正規表記::
INUKAI Norio


== 氏名の構成

=== 姓および名

姓（family name）::
犬飼

名（given name）::
規雄

=== 読み

姓（family name）の読み::
いぬかい

名（given name）の読み::
のりお

読みの文字種::
ひらがな、カタカナのいずれも許容する。

=== 氏名順

正規::
姓、名（family name, given name）

許容::
given name, family name

=== 区切り文字

正規::
区切りなし

許容::
任意


== JIS X 0213 による表記

=== 姓

表記::
犬飼

面区点::
+
----
1-24-4
1-27-84
----

=== 名

表記::
規雄

面区点::
+
----
1-21-12
1-45-26
----

=== 氏名順

正規::
姓、名

=== 区切り

正規::
区切りなし

許容::
任意


== JIS X 0208 による表記

=== 姓

表記::
犬飼

区点::
+
----
24-4
27-84
----

=== 名

表記::
規雄

区点::
+
----
21-12
45-26
----

=== 氏名順

正規::
姓、名

=== 区切り

正規::
区切りなし

許容::
任意

== ISO/IEC 10646 による表記

=== 姓

表記::
犬飼

符号位置列::
+
----
U+72AC
U+98FC
----

IVS::
なし

=== 名

表記::
規雄

符号位置列::
+
----
U+898F
U+96C4
----

IVS::
なし

=== 氏名順

正規::
姓、名

=== 区切り文字

正規::
区切りなし

許容::
任意

=== 正規化

Unicode正規化について::
規定なし


== JIS X 0201 による写像

JIS X 0201による片仮名への写像では、氏名の読みを片仮名で表記する。

この写像は単射であることを要求しない。

NOTE: ラテン文字への写像は「ISO/IEC 646 による写像」を参照する。

=== 姓

正規表記::
ｲﾇｶｲ

=== 名

正規表記::
ﾉﾘｵ

=== 氏名順

正規::
姓、名


=== 区切り文字

正規::
区切りなし

許容::
任意


== ISO/IEC 646 による写像

ISO/IEC 646では、JIS X 0213等による氏名と異なる文字列への写像を許容する。

この写像は単射であることを要求しない。

=== 姓

正規表記::
INUKAI

許容表記::
+
----
Inukai
inukai
----

=== 名

正規表記::
Norio

許容表記::
+
----
NORIO
norio
----

=== 氏名順

正規::
姓、名（family name, given name）

許容::
名、姓

=== 区切り文字

正規::
SPACE

許容::
任意

=== 氏名全体

正規表記::
+
----
INUKAI Norio
----

許容表記::
姓および名の各許容表記、許容される氏名順ならびに許容される区切り文字の組合せを許容する。

=== ローマ字表記

方式::
任意

== Pronouns

英語で本人を指示する場合のpronounsについて、次の表記を使用する。

正規::
he/him

== 表記の優先

各文字集合または符号化体系について本文書に正規表記が明示されている場合、
読み、ローマ字化方式その他の規則から表記を再生成するのではなく、
明示された正規表記を優先する。

許容表記が明示されている場合、その表記も本人の氏名の表記として許容する。

「任意」とされた事項については、本文書による表記上の制約を設けない。

「規定なし」とされた事項については、本文書はその表記の可否を判断しない。
